### ISSUE TITLE
Expressions.Test build issues

### ISSUE THREAD

**Issue by locsius** [NMFCode/NMF#36] opened 2018-02-24 19:47 UTC
Hello!

I was having issues building this project when I built the entire solution after checking it out from github.  It was giving me grief about the .tt files, so I removed the clarius reference and added the following to the top of the .csproj:

<PropertyGroup>
    <TTToolsPath>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\TextTemplating</TTToolsPath>  
  </PropertyGroup>
  <Import Project="$(TTToolsPath)\Microsoft.TextTemplating.targets" />
 
now it works by dotnet msbuild and from the solution.

Thanks -
scott

**Comment by georghinkel** [comment] 2018-03-01 10:36
Hi,

yeah, there have been a range of problems attached to include the execution of text templates into the build process. Unfortunately, these problems are not really solved yet, so that I am thinking about checking the generated code files into the repository in order to avoid those problems.

As a reason, the path to the text templating tools are no longer agnostic of Visual Studio. Rather, as you see at the path you posted, the path depends on the Visual Studio version (and even edition) you use.

Best,

Georg

**Comment by locsius** [comment] 2018-03-02 03:05
Right on - thanks for the info.  Nice product!

**Comment by georghinkel** [comment] 2018-03-03 22:31
Just of curiosity: Can you tell me what you are using NMF for and in particular which parts of it? Only the model representation or also the incrementalization system, the transformation engine or even the synchronization engine?

**Comment by locsius** [comment] 2018-03-04 00:27
Hey Geoge -

So I started off wanting to use NMF to convert ecore to something I could
deal with in .net.  It worked fine for a few UML DDD models that I put
together, so that was great.  However, now I'm messing around with this
jUCMNav and TouchCore software that's being made at McGill -- have you seen
it?  My end goal is to be able to take the models created from these apps
and generate a .net core system that works.

What sounds interesting to you these days?

-se

**Comment by georghinkel** [comment] 2018-03-13 14:22
Hi,

yes, I have seen TouchCore. It is not too long ago that we had Jörg Kienzle as a guest researcher in our group. Would be very nice to be able to use it as an editor for NMF, because NMF itself currently does not have an editor at all.

For the purpose, I guess the effort to do that will depend on whether the resulting model should be executable alone or to be extended with custom logic or not. The current code generator in NMF basically does not add any executable behavior except for things implied by the metamodel structure (e.g. to implement bidirectional references and compositions, but also to implement notifications). However, the code generator is actually available as a library and gives you a fully modifiable code model and a trace how metamodel elements have been transformed.

Because you asked, the most interesting use cases for me are those that really use NMFs ability to execute model transformations or analyses in an incremental manner by creating a dynamic dependency graph. 

Best,

Georg

**Comment by mcintyre321** [comment] 2018-03-15 10:07
I'm having a problem where the t4s are being run by VS, including the TestGenerationSettings.t4 file which is an import for other templates.

That TestGenerationSettings.t4 doesn't run as a standalone T4 template.

**Comment by georghinkel** [comment] 2018-06-28 10:01
@mcintyre321 What is the problem that the TestGenerationSettings.t4 does not run as a standalone T4 template?

**Comment by mcintyre321** [comment] 2018-06-28 11:30
You get this when you download and build in a standard VS2017 instance:

![image](https://user-images.githubusercontent.com/275706/42031654-f3555c68-7ace-11e8-82ff-4a841449bc32.png)

**Comment by georghinkel** [comment] 2018-06-28 16:10
Hm, I recently also had to setup a new VS 2017 as I changed my machine. However, I cannot reproduce this issue. 

The only thing that I can imagine: I vaguely remember that somebody said that the DSL tools (which I have installed locally) are changing some things in the T4 engine. You could try this. It is installable simply through the VS installer, but you have to look for it in the single components list, it is not included in a workflow.

**Comment by georghinkel** [comment] 2019-08-06 17:19
Closing as cannot reproduce

**Closed by georghinkel** 2019-08-06 17:19 UTC
Labels: question
